version: '3.4'

x-wordpress: &wordpress
  build: ./
  image: hackwagon_wordpress
  entrypoint: /bin/bash -c "echo \"define('WP_HOME', 'http://$$SITENAME');define('WP_SITEURL', 'http://$$SITENAME');\" >> /usr/src/wordpress/wp-config-sample.php && docker-entrypoint.sh apache2-foreground"
  restart: always
  environment:
    WORDPRESS_DB_HOST: db
    WORDPRESS_DB_USER: hackwagon
    WORDPRESS_DB_PASSWORD: hackwagon
    WORDPRESS_DB_NAME: hackwagon

x-db: &db
  image: mysql:5.7
  restart: always
  environment:
    MYSQL_DATABASE: hackwagon
    MYSQL_USER: hackwagon
    MYSQL_PASSWORD: hackwagon
    MYSQL_ROOT_PASSWORD: 'CS101_SuperSecurePassword'

services:
  wp_team_1:
    <<: *wordpress
    ports:
      - "8001:80"
      - "4441:4441"
    environment:
      SITENAME: "challenges.supersecurity.cf:8001"
      WORDPRESS_DB_NAME: hackwagon1


  # db_team_1:
  #   <<: *db
  #   volumes:
  #     - ../docker-entrypoint-initdb.d/hackwagon1.sql.gz:/docker-entrypoint-initdb.d/hackwagon1.sql.gz:ro

  wp_team_2:
    <<: *wordpress
    ports:
      - "8002:80"
      - "4442:4442"
    environment:
      SITENAME: "challenges.supersecurity.cf:8002"
      WORDPRESS_DB_NAME: hackwagon2


  # db_team_2:
  #   <<: *db
  #   volumes:
  #     - ../docker-entrypoint-initdb.d/hackwagon2.sql.gz:/docker-entrypoint-initdb.d/hackwagon2.sql.gz:ro

  wp_team_3:
    <<: *wordpress
    ports:
      - "8003:80"
      - "4443:4443"
    environment:
      SITENAME: "challenges.supersecurity.cf:8003"
      WORDPRESS_DB_NAME: hackwagon3


  # db_team_3:
  #   <<: *db
  #   volumes:
  #     - ../docker-entrypoint-initdb.d/hackwagon3.sql.gz:/docker-entrypoint-initdb.d/hackwagon3.sql.gz:ro

  wp_team_4:
    <<: *wordpress
    ports:
      - "8004:80"
      - "4444:4444"
    environment:
      SITENAME: "challenges.supersecurity.cf:8004"
      WORDPRESS_DB_NAME: hackwagon4


  # db_team_4:
  #   <<: *db
  #   volumes:
  #     - ../docker-entrypoint-initdb.d/hackwagon4.sql.gz:/docker-entrypoint-initdb.d/hackwagon4.sql.gz:ro

  wp_team_5:
    <<: *wordpress
    ports:
      - "8005:80"
      - "4445:4445"
    environment:
      SITENAME: "challenges.supersecurity.cf:8005"
      WORDPRESS_DB_NAME: hackwagon5


  # db_team_5:
  #   <<: *db
  #   volumes:
  #     - ../docker-entrypoint-initdb.d/hackwagon5.sql.gz:/docker-entrypoint-initdb.d/hackwagon5.sql.gz:ro

  wp_team_6:
    <<: *wordpress
    ports:
      - "8006:80"
      - "4446:4446"
    environment:
      SITENAME: "challenges.supersecurity.cf:8006"
      WORDPRESS_DB_NAME: hackwagon6


  # db_team_6:
  #   <<: *db
  #   volumes:
  #     - ../docker-entrypoint-initdb.d/hackwagon6.sql.gz:/docker-entrypoint-initdb.d/hackwagon6.sql.gz:ro

  wp_team_7:
    <<: *wordpress
    ports:
      - "8007:80"
      - "4447:4447"
    environment:
      SITENAME: "challenges.supersecurity.cf:8007"
      WORDPRESS_DB_NAME: hackwagon7


  # db_team_7:
  #   <<: *db
  #   volumes:
  #     - ../docker-entrypoint-initdb.d/hackwagon7.sql.gz:/docker-entrypoint-initdb.d/hackwagon7.sql.gz:ro

  wp_team_8:
    <<: *wordpress
    ports:
      - "8008:80"
      - "4448:4448"
    environment:
      SITENAME: "challenges.supersecurity.cf:8008"
      WORDPRESS_DB_NAME: hackwagon8


  # db_team_8:
  #   <<: *db
  #   volumes:
  #     - ../docker-entrypoint-initdb.d/hackwagon8.sql.gz:/docker-entrypoint-initdb.d/hackwagon8.sql.gz:ro

  wp_team_9:
    <<: *wordpress
    ports:
      - "8009:80"
      - "4449:4449"
    environment:
      SITENAME: "challenges.supersecurity.cf:8009"
      WORDPRESS_DB_NAME: hackwagon9


  # db_team_9:
  #   <<: *db
  #   volumes:
  #     - ../docker-entrypoint-initdb.d/hackwagon9.sql.gz:/docker-entrypoint-initdb.d/hackwagon9.sql.gz:ro

  wp_team_10:
    <<: *wordpress
    ports:
      - "8010:80"
      - "4450:4450"
    environment:
      SITENAME: "challenges.supersecurity.cf:8010"
      WORDPRESS_DB_NAME: hackwagon10


  # db_team_10:
  #   <<: *db
  #   volumes:
  #     - ../docker-entrypoint-initdb.d/hackwagon10.sql.gz:/docker-entrypoint-initdb.d/hackwagon10.sql.gz:ro
